### ISSUE TITLE
Proceed with the Django Girls tutorial

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-makkaronis4e#11]
Do a PR per each tutorial page.

**Comment by makkaronis4e** [comment]
-

- [ ] еу

**Comment by makkaronis4e** [comment]
- [x] Django installation #12 

- [x] Django models #12 

- [x] Django admin #12 

- [x] Deploy  

- [x] Add a page with blog posts list #15

- [x] Create HTML for site #15

- [x] Link post with template #16

- [x] Add CSS for site #17 

- [ ]  Finish with tutorial
